
spring:
  application:
    name: bluemoon-edtech
  datasource:
    url: jdbc:postgresql://localhost:5432/edtech_db
    username: postgres
    password: NewStrongPassword123
  jpa:
    hibernate:
      ddl-auto: update     # <-- this tells Hibernate to create/update tables
    show-sql: true         # <-- prints SQL to logs
    properties:
      hibernate:
        format_sql: false


jwt:
  secret: manchester_is_always_blue_will_be_blue_and_forever
  expiration-ms: 900000  # 1 day in ms

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: nilayansamanta4@gmail.com

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] [%X{userId}] %-5level %logger{36} - %msg%n"


server:
  port: 8081
admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  name:  ${ADMIN_NAME}
